
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jun 21 22:52:09 CEST 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LTE = 39;
  public static final int LBRACKET = 15;
  public static final int CHAR = 44;
  public static final int CONST = 14;
  public static final int LPAREN = 6;
  public static final int SEMI = 5;
  public static final int CONTINUE = 24;
  public static final int VARARG = 53;
  public static final int MINUS = 32;
  public static final int RPAREN = 7;
  public static final int AND = 41;
  public static final int LT = 38;
  public static final int RECORD = 19;
  public static final int OR = 29;
  public static final int COMMA = 11;
  public static final int CLASS = 17;
  public static final int INC = 27;
  public static final int DIV = 33;
  public static final int PLUS = 10;
  public static final int IF = 47;
  public static final int ASSIGN = 30;
  public static final int THIS = 51;
  public static final int DOT = 42;
  public static final int BOOLEAN = 45;
  public static final int EOF = 0;
  public static final int RETURN = 9;
  public static final int RBRACKET = 16;
  public static final int EQUAL = 8;
  public static final int SUPER = 49;
  public static final int NEW = 40;
  public static final int error = 1;
  public static final int MUL = 31;
  public static final int NUMBER = 43;
  public static final int MOD = 34;
  public static final int IDENT = 46;
  public static final int BREAK = 23;
  public static final int VOID = 13;
  public static final int GTE = 37;
  public static final int COLON = 20;
  public static final int ELSE = 48;
  public static final int LBRACE = 3;
  public static final int ENUM = 50;
  public static final int READ = 25;
  public static final int GOTO = 26;
  public static final int WHILE = 22;
  public static final int NEQUAL = 35;
  public static final int RBRACE = 4;
  public static final int EXTENDS = 18;
  public static final int PROG = 2;
  public static final int DEC = 28;
  public static final int GT = 36;
  public static final int EXPONENT = 52;
  public static final int PRINT = 12;
  public static final int DO = 21;
}

